### ISSUE TITLE
Protect getSubset from "index creation attacks"

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-subset-rpc#9]
One vulnerability I just discovered with `getSubset` and JITDB:

A remote peer could send N `getSubset` requests for the queries:

- `{author, type: 'attack1'}`
- `{author, type: 'attack2'}`
- ...
- `{author, type: 'attackN'}`

Where N is large enough so that N multiplied by the average JITDB bitvector index file becomes so large that it consumes all disk space available. We have to protect the usage of `getSubset` so that indexes created are purely in memory, OR the type index is always a prefix one (such that all queries will share it).

cc @arj03

**Comment by arj03** [comment]
We could use a special prefix operator for this as you say, but good spotting!
